### ISSUE TITLE
Random failed DNS lookup issues with internal and external DNS

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/k3s-gitops#18]
I am seeing some strange issues with connectivity within the cluster, randomly failed DNS lookups, possibly related to coredns. It happens quite often.

For example, sonarr and radarr are having troubles sometimes connecting to nzbget, qbittorrent, jacket and nzbhydra2. I am using the service addresses, so I am unsure why there's so many issues. Sometimes there's also issues resolving external DNS too like torrent trackers.

**Comment by onedr0p** [comment]
Example stack trace from Sonarr:

```bash
[v3.0.3.698] NzbDrone.Core.Download.Clients.DownloadClientUnavailableException: Unable to connect to NzbGet. DNS Name Resolution Failure: 'nzbget.default.svc.cluster.local' ---> System.Net.WebException: DNS Name Resolution Failure: 'nzbget.default.svc.cluster.local'
  at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) [0x0015a] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:95 
  at NzbDrone.Common.Http.HttpClient.ExecuteRequest (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookieContainer) [0x00080] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\HttpClient.cs:123 
  at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) [0x00008] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\HttpClient.cs:59 
  at NzbDrone.Core.Download.Clients.Nzbget.NzbgetProxy.ProcessRequest[T] (NzbDrone.Core.Download.Clients.Nzbget.NzbgetSettings settings, System.String method, System.Object[] parameters) [0x0003b] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\Nzbget\NzbgetProxy.cs:241 
   --- End of inner exception stack trace ---
  at NzbDrone.Core.Download.Clients.Nzbget.NzbgetProxy.ProcessRequest[T] (NzbDrone.Core.Download.Clients.Nzbget.NzbgetSettings settings, System.String method, System.Object[] parameters) [0x00087] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\Nzbget\NzbgetProxy.cs:254 
  at NzbDrone.Core.Download.Clients.Nzbget.NzbgetProxy.GetGlobalStatus (NzbDrone.Core.Download.Clients.Nzbget.NzbgetSettings settings) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\Nzbget\NzbgetProxy.cs:134 
  at NzbDrone.Core.Download.Clients.Nzbget.Nzbget.GetQueue () [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\Nzbget\Nzbget.cs:54 
  at NzbDrone.Core.Download.Clients.Nzbget.Nzbget.GetItems () [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\Nzbget\Nzbget.cs:184 
  at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientDownloads (NzbDrone.Core.Download.IDownloadClient downloadClient) [0x0000c] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\TrackedDownloads\DownloadMonitoringService.cs:93 
```

**Comment by onedr0p** [comment]
Possibly Related: https://github.com/rancher/k3s/issues/535

**Comment by onedr0p** [comment]
Turning on logging in coredns 

```
kubectl -n kube-system edit configmap coredns
```

```yaml
apiVersion: v1
data:
  Corefile: |
    .:53 {
        log
        errors
        health
        ready
...
```

And trying to get radarr to connect to nzbget provides no logs in coredns.

```
k logs pod/coredns-d798c9dd-nhvk7 -n kube-system -f
```

**Comment by onedr0p** [comment]
Radarr logs about unable to connect to a torrent indexer:

```
2020-2-19 08:50:03.7|Warn|PassThePopcorn|Unable to connect to indexer

[v3.0.0.2622] System.Net.WebException: Resource temporarily unavailable Resource temporarily unavailable: 'https://passthepopcorn.me/torrents.php?action=advanced&json=noredirect&searchstr='
 ---> System.Net.WebException: Resource temporarily unavailable Resource temporarily unavailable
 ---> System.Net.Http.HttpRequestException: Resource temporarily unavailable
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in d:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 145
   --- End of inner exception stack trace ---
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in d:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 145
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in d:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 125
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in d:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 59
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in d:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 306
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in d:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 291
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in d:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 324
```

**Comment by onedr0p** [comment]
and now DNS is working again. I didn't do anything 😢

**Comment by jp83** [comment]
I saw you had this issue the other day, and I'm having a problem now where nzbget can't resolve news servers.  My rancher deployed k8s v1.31 cluster is a little older (working on updating) and still has kube-dns.  From the host I can nslookup fine, and from rancher into the pod/container I can even nslookup. fine  Really confused.  Any ideas to further debug, I've searched since last night but figured you might be familiar recently.

Problem started last weekend when a few small changes related to tweaks swapping from Unifi to Ruckus APs and my Edgerouter Lite stopped giving out DHCP or untagged something on my HP switch and I went ahead and bit the bullet while I had down time to migrate over to Mikrotik router and Brocade ICX switch I'd been putting off.  Obviously that's a can of worms but it's mostly working fine now.

**Comment by onedr0p** [comment]
@jp83 do you by any chance use search domains in your network config on the hosts? This may be an interesting read if you containers are not resolving DNS

https://pracucci.com/kubernetes-dns-resolution-ndots-options-and-why-it-may-affect-application-performances.html

**Comment by jp83** [comment]
Hm, interesting, except my issue isn't intermittent or a loading issue, it's just dead even though I run through all the "[tests](https://rancher.com/docs/rancher/v2.x/en/troubleshooting/dns/)" and it's fine.  I have upgraded and now on coredns.  I do have search name for my network, it's the internal subdomain from my DHCP.

on a node:
```
more /etc/resolv.conf
search int.mydomain.com
nameserver 192.168.2.1
```

exec from within a pod:
```
nameserver 10.43.0.10
search default.svc.cluster.local svc.cluster.local cluster.local int.mydomain.com
options ndots:5

root@nzbget-64bcc75656-5vpvk:/# nslookup google.com
Server:         10.43.0.10
Address:        10.43.0.10:53

Non-authoritative answer:
Name:   google.com
Address: 2607:f8b0:4000:817::200e

Non-authoritative answer:
Name:   google.com
Address: 172.217.14.174

root@nzbget-64bcc75656-5vpvk:/# ping google.com
**ping: bad address 'google.com'**

root@nzbget-64bcc75656-5vpvk:/# ping 172.217.14.174
PING 172.217.14.174 (172.217.14.174): 56 data bytes
64 bytes from 172.217.14.174: seq=0 ttl=54 time=3.169 ms

```

I turned on logging and see it appending my search like:
`2020-02-26T04:10:04.809Z [INFO] 10.42.3.6:36746 - 26447 "AAAA IN github.com.int.mydomain.com. udp 51 false 512" NOERROR qr,rd,ra 454 0.009237919s`

Is that supposed to happen as it searches?  I tried changing the config map to `forward . 8.8.8.8` instead of `forward . /etc/resolv.conf` but didn't seem to help.

**Comment by onedr0p** [comment]
Can you try to remove the search domain and see what happens? 

Also try to set `options ndots:1` in the nzbget container.

**Comment by jp83** [comment]
That seems to fix it for me, I removed search in /etc/resolv.conf on each host and rebooted which didn't seem to help and then manually modified the deployment with the ndots:1 dns option which did the trick.  Still something kind of weird because I fired up a new test cluster and it worked by default.  Eventually I'll end up rebuilding again, but glad I didn't _have_ to this time around.

**Comment by onedr0p** [comment]
Glad to hear! This was an issue driving me crazy for awhile and I had to do a lot research and testing to get to that point.

**Comment by onedr0p** [comment]
I haven't had this issue in over a month, it seems to fix itself. Closing issue.
